// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOINp9HtmQUbN0fO6SuWp4bFNxjEEAekU',
    appId: '1:552463550352:web:e19f41cfbc4960a3335515',
    messagingSenderId: '552463550352',
    projectId: 'todoapp-ac201',
    authDomain: 'todoapp-ac201.firebaseapp.com',
    storageBucket: 'todoapp-ac201.appspot.com',
    measurementId: 'G-J16YKBR40P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt5t-XkaLEjJDF6WUfPGrNk7rPkCufxDs',
    appId: '1:552463550352:android:720116c09d7623f3335515',
    messagingSenderId: '552463550352',
    projectId: 'todoapp-ac201',
    storageBucket: 'todoapp-ac201.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUh4LEQrn6xhAib7BjyzNUCzbku6q2Ucc',
    appId: '1:552463550352:ios:c5582b9e373a78aa335515',
    messagingSenderId: '552463550352',
    projectId: 'todoapp-ac201',
    storageBucket: 'todoapp-ac201.appspot.com',
    iosClientId: '552463550352-6cb9gj84ndctihheaeij88i9ttenmmek.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAppExampleMy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUh4LEQrn6xhAib7BjyzNUCzbku6q2Ucc',
    appId: '1:552463550352:ios:c5582b9e373a78aa335515',
    messagingSenderId: '552463550352',
    projectId: 'todoapp-ac201',
    storageBucket: 'todoapp-ac201.appspot.com',
    iosClientId: '552463550352-6cb9gj84ndctihheaeij88i9ttenmmek.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAppExampleMy',
  );
}
